CREATE TABLE [adi].[Amerigroup_AltusAceGap] (
    [Amerigroup_AltusAceGapKey]   INT           IDENTITY (1, 1) NOT NULL,
    [OriginalFileName]            VARCHAR (100) NOT NULL,
    [SrcFileName]                 VARCHAR (100) NOT NULL,
    [LoadDate]                    DATE          NOT NULL,
    [CreatedDate]                 DATETIME      CONSTRAINT [DF_Amerigroup_AltusAceGap1] DEFAULT (getdate()) NULL,
    [DataDate]                    DATE          NOT NULL,
    [FileDate]                    DATE          NOT NULL,
    [CreatedBy]                   VARCHAR (50)  CONSTRAINT [DF_Amerigroup_AltusAceGap2] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]             DATETIME      CONSTRAINT [DF_Amerigroup_AltusAceGap3] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]               VARCHAR (50)  CONSTRAINT [DF_Amerigroup_AltusAceGap4] DEFAULT (suser_sname()) NOT NULL,
    [PROV_TIN]                    VARCHAR (20)  NULL,
    [PROV_TIN_NAME]               VARCHAR (50)  NULL,
    [MCID]                        VARCHAR (20)  NULL,
    [MONTH_RUN]                   VARCHAR (20)  NULL,
    [MBR_SOR_SYSTEM]              VARCHAR (20)  NULL,
    [REGION]                      VARCHAR (20)  NULL,
    [PRODUCT_DESCRIPTION]         VARCHAR (50)  NULL,
    [CMS_CONTRACT]                VARCHAR (20)  NULL,
    [MEDICARE_ID]                 VARCHAR (20)  NULL,
    [HCID]                        VARCHAR (20)  NULL,
    [MEMLNAME]                    VARCHAR (20)  NULL,
    [MEMFNAME]                    VARCHAR (20)  NULL,
    [MEM_DOB]                     DATE          NULL,
    [GENDER]                      VARCHAR (10)  NULL,
    [PRODUCT_TYPE]                VARCHAR (20)  NULL,
    [MEM_ADDR1]                   VARCHAR (50)  NULL,
    [MEM_ADDR2]                   VARCHAR (50)  NULL,
    [MEM_CITY]                    VARCHAR (30)  NULL,
    [MEM_STATE]                   VARCHAR (20)  NULL,
    [MEM_ZIP]                     VARCHAR (15)  NULL,
    [Ethnicity]                   VARCHAR (10)  NULL,
    [MEM_PHONE]                   VARCHAR (20)  NULL,
    [COUNTY_NAME]                 VARCHAR (20)  NULL,
    [Lang_NM]                     VARCHAR (20)  NULL,
    [Lang_CD]                     VARCHAR (20)  NULL,
    [EMP_MASTER]                  VARCHAR (20)  NULL,
    [EMP_GROUP]                   VARCHAR (20)  NULL,
    [PBP_NBR]                     VARCHAR (20)  NULL,
    [PROV_NPI]                    VARCHAR (20)  NULL,
    [PROV_LAST_NAME]              VARCHAR (20)  NULL,
    [PROV_FIRST_NAME]             VARCHAR (20)  NULL,
    [PROV_NAME]                   VARCHAR (20)  NULL,
    [PROV_PRAC_ADDR1]             VARCHAR (50)  NULL,
    [PROV_PRAC_CITY]              VARCHAR (20)  NULL,
    [PROV_PRAC_STATE]             VARCHAR (20)  NULL,
    [PROV_PRAC_ZIP]               VARCHAR (15)  NULL,
    [PROV_PRAC_COUNTY]            VARCHAR (20)  NULL,
    [PROV_PRAC_PH1]               VARCHAR (20)  NULL,
    [PROV_PRAC_FAX]               VARCHAR (20)  NULL,
    [PGID]                        VARCHAR (20)  NULL,
    [BCS]                         VARCHAR (20)  NULL,
    [BCS_ServiceDate]             DATE          NULL,
    [BCS_FILE_ID]                 VARCHAR (20)  NULL,
    [BCS_FILE_DESC]               VARCHAR (50)  NULL,
    [CBP]                         VARCHAR (20)  NULL,
    [CBP_LastServiceDate]         DATE          NULL,
    [CBP_HypTenDiagDate]          DATE          NULL,
    [CBP_HypTenDiagDate2]         DATE          NULL,
    [CBP_FILE_ID]                 VARCHAR (20)  NULL,
    [CBP_FILE_DESC]               VARCHAR (50)  NULL,
    [CDC_HbA1c_Test]              VARCHAR (20)  NULL,
    [CDC_HbA1c_Test_ServiceDate]  DATE          NULL,
    [CDC_HbA1c_Test_FILE_ID]      VARCHAR (20)  NULL,
    [CDC_HbA1c_Test_FILE_DESC]    VARCHAR (50)  NULL,
    [CDC_HbA1c_LE9]               VARCHAR (20)  NULL,
    [CDC_HBA1C_LE9_ServiceDate]   DATE          NULL,
    [CDC_LastHbA1c_Value]         VARCHAR (20)  NULL,
    [CDC_HbA1c_LE9_FILE_ID]       VARCHAR (20)  NULL,
    [CDC_HbA1c_LE9_FILE_DESC]     VARCHAR (50)  NULL,
    [CDC_EyeExam]                 VARCHAR (20)  NULL,
    [Eye_Exam_TestDate]           DATE          NULL,
    [CDC_EyeExam_FILE_ID]         VARCHAR (20)  NULL,
    [CDC_EyeExam_FILE_DESC]       VARCHAR (50)  NULL,
    [CDC_Nephro]                  VARCHAR (20)  NULL,
    [Nephro_FirstAvailServDate]   DATE          NULL,
    [CDC_Nephro_FILE_ID]          VARCHAR (20)  NULL,
    [CDC_Nephro_FILE_DESC]        VARCHAR (50)  NULL,
    [KED]                         VARCHAR (20)  NULL,
    [KED_ServiceDate]             DATE          NULL,
    [KED_FILE_ID]                 VARCHAR (20)  NULL,
    [KED_FILE_DESC]               VARCHAR (50)  NULL,
    [COA_ACP]                     VARCHAR (20)  NULL,
    [ACP_ServiceDate]             DATE          NULL,
    [COA_ACP_FILE_ID]             VARCHAR (20)  NULL,
    [COA_ACP_FILE_DESC]           VARCHAR (50)  NULL,
    [COA_FSA]                     VARCHAR (20)  NULL,
    [FSA_ServiceDate]             DATE          NULL,
    [COA_FSA_FILE_ID]             VARCHAR (20)  NULL,
    [COA_FSA_FILE_DESC]           VARCHAR (50)  NULL,
    [COA_MR]                      VARCHAR (20)  NULL,
    [MR_ServiceDate]              DATE          NULL,
    [COA_MR_FILE_ID]              VARCHAR (20)  NULL,
    [COA_MR_FILE_DESC]            VARCHAR (50)  NULL,
    [COA_PS]                      VARCHAR (20)  NULL,
    [PS_ServiceDate]              DATE          NULL,
    [COA_PS_FILE_ID]              VARCHAR (20)  NULL,
    [COA_PS_FILE_DESC]            VARCHAR (50)  NULL,
    [COL]                         VARCHAR (20)  NULL,
    [COL_Max_ServiceDate]         DATE          NULL,
    [COL_FILE_ID]                 VARCHAR (20)  NULL,
    [COL_FILE_DESC]               VARCHAR (50)  NULL,
    [OSW]                         VARCHAR (20)  NULL,
    [OSW_ServiceDate]             DATE          NULL,
    [OSW_FILE_ID]                 VARCHAR (20)  NULL,
    [OSW_FILE_DESC]               VARCHAR (50)  NULL,
    [OMW]                         VARCHAR (50)  NULL,
    [OMW_ServiceDate]             DATE          NULL,
    [OMW_Fracture_Date]           DATE          NULL,
    [OMW_FILE_ID]                 VARCHAR (50)  NULL,
    [OMW_FILE_DESC]               VARCHAR (50)  NULL,
    [AOMW]                        VARCHAR (20)  NULL,
    [AOMW_ServiceDate]            DATE          NULL,
    [AOMW_FRACTURE_DATE]          DATE          NULL,
    [AOMW_FILE_ID]                VARCHAR (20)  NULL,
    [AOMW_FILE_DESC]              VARCHAR (50)  NULL,
    [SPC_REC_TOTAL]               VARCHAR (20)  NULL,
    [SPC_REC_RxServiceDate]       DATE          NULL,
    [SPC_REC_FILE_ID]             VARCHAR (20)  NULL,
    [SPC_REC_FILE_DESC]           VARCHAR (50)  NULL,
    [FUH_Followup_30]             VARCHAR (20)  NULL,
    [FUH_30_LastServiceDate]      DATE          NULL,
    [FUH_30_Last_Discharge_Date]  DATE          NULL,
    [FUH_30_FILE_ID]              VARCHAR (20)  NULL,
    [FUH_30_FILE_DESC]            VARCHAR (50)  NULL,
    [FUH_Followup_7]              VARCHAR (20)  NULL,
    [FUH_7_LastServiceDate]       DATE          NULL,
    [FUH_7_Last_Discharge_Date]   DATE          NULL,
    [FUH_7_FILE_ID]               VARCHAR (20)  NULL,
    [FUH_7_FILE_DESC]             VARCHAR (50)  NULL,
    [TRC_ENGAGEMENT]              VARCHAR (20)  NULL,
    [TRC_ENG_LastServiceDate]     DATE          NULL,
    [TRC_Eng_Last_Discharge_Date] DATE          NULL,
    [TRC_Eng_FILE_ID]             VARCHAR (50)  NULL,
    [TRC_Eng_FILE_DESC]           VARCHAR (100) NULL,
    [TRC_RECONCILIATION]          VARCHAR (50)  NULL,
    [TRC_REC_LastServiceDate]     DATE          NULL,
    [TRC_Rec_Last_Discharge_Date] DATE          NULL,
    [TRC_Rec_FILE_ID]             VARCHAR (50)  NULL,
    [TRC_Rec_FILE_DESC]           VARCHAR (100) NULL,
    [RowStatus]                   TINYINT       DEFAULT ((0)) NULL,
    [PROV_SPECIALTY]              VARCHAR (100) NULL,
    [MBRSHP_SOR_CD]               VARCHAR (10)  NULL,
    [CASS_Results]                VARCHAR (50)  NULL,
    [Cass_Check]                  VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([Amerigroup_AltusAceGapKey] ASC)
);

