CREATE TABLE [adi].[Amerigroup_Quality_ProvdrGroup_MemberSummary] (
    [Amerigroup_Quality_ProvdrGroup_MemberSummaryKey] INT             IDENTITY (1, 1) NOT NULL,
    [OriginalFileName]                                VARCHAR (100)   NOT NULL,
    [SrcFileName]                                     VARCHAR (100)   NOT NULL,
    [LoadDate]                                        DATE            NOT NULL,
    [CreatedDate]                                     DATETIME        CONSTRAINT [Amerigroup_Quality_ProvdrGroup_MemberSummary1] DEFAULT (getdate()) NULL,
    [DataDate]                                        DATE            NOT NULL,
    [FileDate]                                        DATE            NOT NULL,
    [CreatedBy]                                       VARCHAR (50)    CONSTRAINT [Amerigroup_Quality_ProvdrGroup_MemberSummary2] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]                                 DATETIME        CONSTRAINT [Amerigroup_Quality_ProvdrGroup_MemberSummary3] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]                                   VARCHAR (50)    CONSTRAINT [Amerigroup_Quality_ProvdrGroup_MemberSummary4] DEFAULT (suser_sname()) NOT NULL,
    [MeasurementYear]                                 VARCHAR (20)    NULL,
    [DateAsOf]                                        DATE            NULL,
    [PCPTin]                                          VARCHAR (20)    NULL,
    [PCPTinName]                                      VARCHAR (50)    NULL,
    [PCPId]                                           VARCHAR (20)    NULL,
    [PCPName]                                         VARCHAR (50)    NULL,
    [MemberId]                                        VARCHAR (20)    NULL,
    [MedicaidId]                                      VARCHAR (50)    NULL,
    [MemberName]                                      VARCHAR (50)    NULL,
    [PlanCode]                                        VARCHAR (20)    NULL,
    [MemberGroupCode]                                 VARCHAR (20)    NULL,
    [MemberDOB]                                       DATE            NULL,
    [MemberGender]                                    VARCHAR (10)    NULL,
    [MemberAddress1]                                  VARCHAR (100)   NULL,
    [MemberCity]                                      VARCHAR (50)    NULL,
    [MemberState]                                     VARCHAR (20)    NULL,
    [MemberZip]                                       VARCHAR (20)    NULL,
    [MemberCounty]                                    VARCHAR (20)    NULL,
    [ClassificationDate]                              DATE            NULL,
    [Date1]                                           DATE            NULL,
    [Measure]                                         VARCHAR (50)    NULL,
    [Sub_Measure]                                     VARCHAR (50)    NULL,
    [W30VisitCount]                                   VARCHAR (10)    NULL,
    [HbA1cTest]                                       VARCHAR (10)    NULL,
    [HbA1cResult]                                     VARCHAR (10)    NULL,
    [LastHbA1cValue]                                  DECIMAL (10, 2) NULL,
    [FocusMeasure]                                    VARCHAR (20)    NULL,
    [Status]                                          VARCHAR (50)    NULL,
    [RowStatus]                                       TINYINT         DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([Amerigroup_Quality_ProvdrGroup_MemberSummaryKey] ASC)
);

