CREATE TABLE [adi].[Amerigroup_MA_WellnessVisits] (
    [Amerigroup_MA_WellnessVisitsKey] INT           IDENTITY (1, 1) NOT NULL,
    [OriginalFileName]                VARCHAR (100) NOT NULL,
    [SrcFileName]                     VARCHAR (100) NOT NULL,
    [LoadDate]                        DATE          NOT NULL,
    [CreatedDate]                     DATETIME      CONSTRAINT [DF_Amerigroup_MA_WellnessVisits1] DEFAULT (getdate()) NULL,
    [DataDate]                        DATE          NOT NULL,
    [FileDate]                        DATE          NOT NULL,
    [CreatedBy]                       VARCHAR (50)  CONSTRAINT [DF_Amerigroup_MA_WellnessVisits2] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]                 DATETIME      CONSTRAINT [DF_Amerigroup_MA_WellnessVisits3] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]                   VARCHAR (50)  CONSTRAINT [DF_Amerigroup_MA_WellnessVisits4] DEFAULT (suser_sname()) NOT NULL,
    [MMR_Year]                        VARCHAR (50)  NULL,
    [ProviderFullName]                VARCHAR (50)  NULL,
    [ProviderNPI]                     VARCHAR (20)  NULL,
    [HICN]                            VARCHAR (50)  NULL,
    [MemberLastName]                  VARCHAR (50)  NULL,
    [MemberFirstName]                 VARCHAR (50)  NULL,
    [MemberBirthDate]                 DATE          NULL,
    [EffectiveDate]                   DATE          NULL,
    [MinProviderAffiliationDate]      DATE          NULL,
    [MaxProviderAffiliationDate]      DATE          NULL,
    [MemberPhone]                     VARCHAR (15)  NULL,
    [MemberAddress]                   VARCHAR (50)  NULL,
    [MemberCity]                      VARCHAR (50)  NULL,
    [MemberState]                     VARCHAR (50)  NULL,
    [MemberZip]                       VARCHAR (10)  NULL,
    [MbrsWithClaims]                  VARCHAR (50)  NULL,
    [MbrsWithOfficeVisits]            VARCHAR (50)  NULL,
    [MbrsWithPCPVisits]               VARCHAR (50)  NULL,
    [MbrsWithWellnessVisits]          VARCHAR (50)  NULL,
    [MbrsWithAnnualPlannedVisits]     VARCHAR (50)  NULL,
    [RowStatus]                       TINYINT       DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([Amerigroup_MA_WellnessVisitsKey] ASC)
);

