CREATE TABLE [adi].[Amerigroup_Quality_ProvdrGroup_ProvdrSummary] (
    [Amerigroup_Quality_ProvdrGroup_ProvdrSummaryKey] INT           IDENTITY (1, 1) NOT NULL,
    [OriginalFileName]                                VARCHAR (100) NOT NULL,
    [SrcFileName]                                     VARCHAR (100) NOT NULL,
    [LoadDate]                                        DATE          NOT NULL,
    [CreatedDate]                                     DATETIME      CONSTRAINT [Amerigroup_Quality_ProvdrGroup_ProvdrSummary1] DEFAULT (getdate()) NULL,
    [DataDate]                                        DATE          NOT NULL,
    [FileDate]                                        DATE          NOT NULL,
    [CreatedBy]                                       VARCHAR (50)  CONSTRAINT [Amerigroup_Quality_ProvdrGroup_ProvdrSummary2] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]                                 DATETIME      CONSTRAINT [Amerigroup_Quality_ProvdrGroup_ProvdrSummary3] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]                                   VARCHAR (50)  CONSTRAINT [Amerigroup_Quality_ProvdrGroup_ProvdrSummary4] DEFAULT (suser_sname()) NOT NULL,
    [MeasurementYear]                                 VARCHAR (20)  NULL,
    [DateAsOf]                                        DATE          NULL,
    [PCPTin]                                          VARCHAR (20)  NULL,
    [PCPTinName]                                      VARCHAR (50)  NULL,
    [PCPId]                                           VARCHAR (20)  NULL,
    [PCPName]                                         VARCHAR (50)  NULL,
    [PCPAddress1]                                     VARCHAR (100) NULL,
    [PCPCity]                                         VARCHAR (50)  NULL,
    [PCPState]                                        VARCHAR (50)  NULL,
    [PCPZipcode]                                      VARCHAR (10)  NULL,
    [PCPPhone]                                        VARCHAR (20)  NULL,
    [PCPFax]                                          VARCHAR (50)  NULL,
    [PCPSpecialty1]                                   VARCHAR (50)  NULL,
    [PCPSpecialty2]                                   VARCHAR (50)  NULL,
    [PCPSpecialty3]                                   VARCHAR (50)  NULL,
    [Measure]                                         VARCHAR (50)  NULL,
    [Sub_Measure]                                     VARCHAR (50)  NULL,
    [FocusMeasure]                                    VARCHAR (50)  NULL,
    [Compliant]                                       INT           NULL,
    [Non_Compliant]                                   INT           NULL,
    [Eligible_Population]                             INT           NULL,
    [RATE]                                            VARCHAR (10)  NULL,
    [NCQA_QC_Target50thPercentile]                    VARCHAR (10)  NULL,
    [MembersTarget_50th]                              VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([Amerigroup_Quality_ProvdrGroup_ProvdrSummaryKey] ASC)
);

