CREATE TABLE [dbo].[z_AmerigroupCareopps] (
    [PROV_TIN]                    INT           NOT NULL,
    [PROV_TIN_NAME]               VARCHAR (50)  NOT NULL,
    [MCID]                        INT           NOT NULL,
    [MONTH_RUN]                   VARCHAR (50)  NOT NULL,
    [MBR_SOR_SYSTEM]              VARCHAR (50)  NOT NULL,
    [REGION]                      VARCHAR (50)  NOT NULL,
    [PRODUCT_DESCRIPTION]         VARCHAR (50)  NOT NULL,
    [CMS_CONTRACT]                VARCHAR (50)  NOT NULL,
    [MEDICARE_ID]                 VARCHAR (50)  NOT NULL,
    [HCID]                        VARCHAR (50)  NOT NULL,
    [MEMLNAME]                    VARCHAR (50)  NOT NULL,
    [MEMFNAME]                    VARCHAR (50)  NOT NULL,
    [MEM_DOB]                     DATETIME2 (7) NOT NULL,
    [GENDER]                      VARCHAR (50)  NOT NULL,
    [PRODUCT_TYPE]                VARCHAR (50)  NOT NULL,
    [MEM_ADDR1]                   VARCHAR (50)  NOT NULL,
    [MEM_ADDR2]                   VARCHAR (1)   NULL,
    [MEM_CITY]                    VARCHAR (50)  NOT NULL,
    [MEM_STATE]                   VARCHAR (50)  NOT NULL,
    [MEM_ZIP]                     VARCHAR (50)  NOT NULL,
    [Ethnicity]                   VARCHAR (50)  NOT NULL,
    [MEM_PHONE]                   FLOAT (53)    NOT NULL,
    [COUNTY_NAME]                 VARCHAR (50)  NULL,
    [Lang_NM]                     NVARCHAR (50) NULL,
    [Lang_CD]                     NVARCHAR (50) NULL,
    [EMP_MASTER]                  NVARCHAR (50) NOT NULL,
    [EMP_GROUP]                   NVARCHAR (50) NOT NULL,
    [PBP_NBR]                     NVARCHAR (50) NOT NULL,
    [PROV_NPI]                    INT           NOT NULL,
    [PROV_LAST_NAME]              NVARCHAR (50) NOT NULL,
    [PROV_FIRST_NAME]             NVARCHAR (50) NOT NULL,
    [PROV_NAME]                   NVARCHAR (50) NOT NULL,
    [PROV_PRAC_ADDR1]             NVARCHAR (50) NOT NULL,
    [PROV_PRAC_CITY]              NVARCHAR (50) NOT NULL,
    [PROV_PRAC_STATE]             NVARCHAR (50) NOT NULL,
    [PROV_PRAC_ZIP]               INT           NOT NULL,
    [PROV_PRAC_COUNTY]            NVARCHAR (50) NOT NULL,
    [PROV_PRAC_PH1]               FLOAT (53)    NOT NULL,
    [PROV_PRAC_FAX]               FLOAT (53)    NOT NULL,
    [PGID]                        NVARCHAR (50) NULL,
    [BCS]                         NVARCHAR (50) NULL,
    [BCS_ServiceDate]             NVARCHAR (50) NULL,
    [BCS_FILE_ID]                 NVARCHAR (50) NULL,
    [BCS_FILE_DESC]               NVARCHAR (50) NULL,
    [CBP]                         NVARCHAR (50) NULL,
    [CBP_LastServiceDate]         NVARCHAR (50) NULL,
    [CBP_HypTenDiagDate]          NVARCHAR (50) NULL,
    [CBP_HypTenDiagDate2]         NVARCHAR (50) NULL,
    [CBP_FILE_ID]                 NVARCHAR (50) NULL,
    [CBP_FILE_DESC]               NVARCHAR (50) NULL,
    [CDC_HbA1c_Test]              NVARCHAR (50) NULL,
    [CDC_HbA1c_Test_ServiceDate]  NVARCHAR (50) NULL,
    [CDC_HbA1c_Test_FILE_ID]      NVARCHAR (50) NULL,
    [CDC_HbA1c_Test_FILE_DESC]    NVARCHAR (50) NULL,
    [CDC_HbA1c_LE9]               NVARCHAR (50) NULL,
    [CDC_HBA1C_LE9_ServiceDate]   NVARCHAR (50) NULL,
    [CDC_LastHbA1c_Value]         NVARCHAR (50) NULL,
    [CDC_HbA1c_LE9_FILE_ID]       NVARCHAR (50) NULL,
    [CDC_HbA1c_LE9_FILE_DESC]     NVARCHAR (50) NULL,
    [CDC_EyeExam]                 NVARCHAR (50) NULL,
    [Eye_Exam_TestDate]           NVARCHAR (50) NULL,
    [CDC_EyeExam_FILE_ID]         NVARCHAR (50) NULL,
    [CDC_EyeExam_FILE_DESC]       NVARCHAR (50) NULL,
    [CDC_Nephro]                  NVARCHAR (50) NULL,
    [Nephro_FirstAvailServDate]   NVARCHAR (50) NULL,
    [CDC_Nephro_FILE_ID]          NVARCHAR (50) NULL,
    [CDC_Nephro_FILE_DESC]        NVARCHAR (50) NULL,
    [KED]                         NVARCHAR (50) NULL,
    [KED_ServiceDate]             NVARCHAR (50) NULL,
    [KED_FILE_ID]                 NVARCHAR (50) NULL,
    [KED_FILE_DESC]               NVARCHAR (50) NULL,
    [COA_ACP]                     NVARCHAR (50) NULL,
    [ACP_ServiceDate]             NVARCHAR (50) NULL,
    [COA_ACP_FILE_ID]             NVARCHAR (50) NULL,
    [COA_ACP_FILE_DESC]           NVARCHAR (50) NULL,
    [COA_FSA]                     NVARCHAR (50) NULL,
    [FSA_ServiceDate]             NVARCHAR (50) NULL,
    [COA_FSA_FILE_ID]             NVARCHAR (50) NULL,
    [COA_FSA_FILE_DESC]           NVARCHAR (50) NULL,
    [COA_MR]                      NVARCHAR (50) NULL,
    [MR_ServiceDate]              NVARCHAR (50) NULL,
    [COA_MR_FILE_ID]              NVARCHAR (50) NULL,
    [COA_MR_FILE_DESC]            NVARCHAR (50) NULL,
    [COA_PS]                      NVARCHAR (50) NULL,
    [PS_ServiceDate]              NVARCHAR (50) NULL,
    [COA_PS_FILE_ID]              NVARCHAR (50) NULL,
    [COA_PS_FILE_DESC]            NVARCHAR (50) NULL,
    [COL]                         NVARCHAR (50) NULL,
    [COL_Max_ServiceDate]         NVARCHAR (50) NULL,
    [COL_FILE_ID]                 NVARCHAR (50) NULL,
    [COL_FILE_DESC]               NVARCHAR (50) NULL,
    [OSW]                         NVARCHAR (50) NULL,
    [OSW_ServiceDate]             NVARCHAR (50) NULL,
    [OSW_FILE_ID]                 NVARCHAR (50) NULL,
    [OSW_FILE_DESC]               NVARCHAR (50) NULL,
    [OMW]                         NVARCHAR (1)  NULL,
    [OMW_ServiceDate]             NVARCHAR (1)  NULL,
    [OMW_Fracture_Date]           NVARCHAR (1)  NULL,
    [OMW_FILE_ID]                 NVARCHAR (1)  NULL,
    [OMW_FILE_DESC]               NVARCHAR (1)  NULL,
    [AOMW]                        NVARCHAR (1)  NULL,
    [AOMW_ServiceDate]            NVARCHAR (1)  NULL,
    [AOMW_FRACTURE_DATE]          NVARCHAR (1)  NULL,
    [AOMW_FILE_ID]                NVARCHAR (1)  NULL,
    [AOMW_FILE_DESC]              NVARCHAR (1)  NULL,
    [SPC_REC_TOTAL]               NVARCHAR (50) NULL,
    [SPC_REC_RxServiceDate]       NVARCHAR (50) NULL,
    [SPC_REC_FILE_ID]             NVARCHAR (50) NULL,
    [SPC_REC_FILE_DESC]           NVARCHAR (50) NULL,
    [FUH_Followup_30]             NVARCHAR (50) NULL,
    [FUH_30_LastServiceDate]      NVARCHAR (50) NULL,
    [FUH_30_Last_Discharge_Date]  NVARCHAR (50) NULL,
    [FUH_30_FILE_ID]              NVARCHAR (50) NULL,
    [FUH_30_FILE_DESC]            NVARCHAR (50) NULL,
    [FUH_Followup_7]              NVARCHAR (50) NULL,
    [FUH_7_LastServiceDate]       NVARCHAR (1)  NULL,
    [FUH_7_Last_Discharge_Date]   NVARCHAR (50) NULL,
    [FUH_7_FILE_ID]               NVARCHAR (1)  NULL,
    [FUH_7_FILE_DESC]             NVARCHAR (1)  NULL,
    [TRC_ENGAGEMENT]              NVARCHAR (50) NULL,
    [TRC_ENG_LastServiceDate]     NVARCHAR (50) NULL,
    [TRC_Eng_Last_Discharge_Date] NVARCHAR (50) NULL,
    [TRC_Eng_FILE_ID]             NVARCHAR (50) NULL,
    [TRC_Eng_FILE_DESC]           NVARCHAR (50) NULL,
    [TRC_RECONCILIATION]          NVARCHAR (50) NULL,
    [TRC_REC_LastServiceDate]     NVARCHAR (1)  NULL,
    [TRC_Rec_Last_Discharge_Date] NVARCHAR (50) NULL,
    [TRC_Rec_FILE_ID]             NVARCHAR (1)  NULL,
    [TRC_Rec_FILE_DESC]           NVARCHAR (1)  NULL
);

